default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  socket: /tmp/mysql.sock
  reconnect: true
  username: root
  password:

development:
  <<: *default
  database: billboard_development

test:
  <<: *default
  database: billboard_test

production:
  <<: *default
  database: billboard_production
  username: billboard
  password: <%= ENV['BILLBOARD_DATABASE_PASSWORD'] %>
